### ISSUE TITLE
IMU order

### ISSUE THREAD

**Issue by mah110mat** [eth-ait/dip18#10]
I'm looking at the data of DIP_IMU_and_Others/DIP_IMU/*.pkl.
I am suspicious of swapping the knees and elbows.
Could anyone make sure of the IMU order?

**Comment by YinghaoHuang91** [comment]
Thanks for spotting this. I just checked the raw data myself. The dataset on the website is not the same as the latest version I have at hand. I'm not sure whether the inconsistency comes from our webpage engineer who failed to manage all the versions or there is some flaw in our data uploading system. I will check with them as soon as possible. I will notify you once the data in the website is updated. 

Thanks again for spotting this problem.

**Comment by mah110mat** [comment]
Thank you very much for your comment.
I'm looking forward to update.

**Comment by YinghaoHuang91** [comment]
I suppose you used the second download link to download the data, right? We confirmed that the second link was connected to an older version of the data. Now we've updated both links again. Can you check the data there once more? Please don't hesitate to get back to us in case you have future issues.

**Comment by mah110mat** [comment]
I downloaded it again from link 1st and got the result as I expected.
Thank you very much for your help!
