### ISSUE TITLE
Can sensor data be directly input to the network without rotating the axis?

### ISSUE THREAD

**Issue by NINGgege111** [eth-ait/dip18#14]
Thank you for your work. I am experimenting with another sensor, but the incoming axis is always different from the unity game. Can you help me solve this problem?

**Comment by YinghaoHuang91** [comment]
Hi the model is trained with rotation and acceleration normalized wrt root joint framewise, so to test it on your own data you also need to do the same normalization. For the details please refer to the Section 4.3 of the paper.
