### ISSUE TITLE
Missing evaluation of positional loss

### ISSUE THREAD

**Issue by nkueng** [eth-ait/dip18#15]
It seems you have removed the functionality to compute the positional loss[ in your evaluation script](https://github.com/eth-ait/dip18/blob/917e6199ffa5eabed2cc8790c6bcd8337f369c3e/train_and_eval/utils.py#L312). Could you either add the respective function for completeness or provide some insight into how you computed the positional loss?

Cheers,
Nicola

**Comment by kaufManu** [comment]
Hi Nicola,

To make sure the positional loss is the same as the one reported by SIP, we ran the computation of this metric offline (i.e. not with the code base here). It was also more compute intensive as it involves a Procrustes alignment step. May be @YinghaoHuang91 could comment more on this?

**Comment by YinghaoHuang91** [comment]
> Hi Nicola,
> 
> To make sure the positional loss is the same as the one reported by SIP, we ran the computation of this metric offline (i.e. not with the code base here). It was also more compute intensive as it involves a Procrustes alignment step. May be @YinghaoHuang91 could comment more on this?

Yes to be compatible with the numbers reported in SIP we also used Procrustes alignment for the positional loss. Since our method doesn't regress body shape, the mean body shape together with the regressed/reference poses are used to compute the positional losses.

**Comment by nkueng** [comment]
Many thanks for the quick response and the pointers. Sparse Inertial Poser was never open-sourced, correct?

Also, since this alignment step is not mentioned in the paper, may I ask for the justification for doing so? 
Doesn't this distort the error measure? 
I'm thinking of a dummy example, where all joints of the prediction are perfectly aligned with the target except for one arm. The alignment would minimize the rotational offset between prediction and target, but also add a positional joint error even to the perfectly predicted joints, no?

Thanks tons for your time!
Cheers, 
Nicola

**Comment by kaufManu** [comment]
Hi Nicola,

Yes, that piece of the code was not open-sourced.

Adding a Procrustes alignment before computing the positional error is a common thing to do in the pose estimation literature. Yes, the error measure is "distorted", but one could argue that this is the intention. Typically, the error measure should give an idea about how correct the *pose* it-self is, i.e. without the influence of global rotations or translations. You could think of a counter-example to yours: the predicted pose is shifted by say 1 m to the right, consequently the error measure will be huge even though the actual pose might still look very similar to reference. The Procrustes alignment step addresses this. Of course, this is not a perfect remedy, illustrated by your example, but it's what's often done. Also, this is why we have the other error metric on the joint angles, to give a more complete picture.

Hope this helps.

Best
Manuel

**Comment by nkueng** [comment]
Thank you, Manuel! That was a great example.
