### ISSUE TITLE
Locations of IMUs in DIP-IMU dataset

### ISSUE THREAD

**Issue by nkueng** [eth-ait/dip18#16]
Dear DIP-authors,

Please excuse my frequent posting here. With this one, at least I hope to provide value to future research by adding to the usability of your open-sourced dataset DIP-IMU!

For my use case of DIP-IMU, I need to know the exact locations of the 17 IMUs on the body. All the information I can find on this is in the `overview_of_published_data.txt` which comes inside the dataset `DIP_IMU_and_Others`:

> The order of IMUs is: [head, spine2, belly, lchest, rchest, lshoulder, rshoulder, lelbow, relbow, lhip, rhip, lknee, rknee, lwrist, lwrist, lankle, rankle].

Sadly, this does not correspond to the [standard Xsens MVN configuration](https://i.pinimg.com/474x/d7/e4/b9/d7e4b9168b8e50e88c10a90589adda39.jpg). I guess you didn't care about tracking feet and hands but instead used those sensors to get more data from the torso.

It would be of most value to me if you could help me figure out where exactly you placed the sensors on the subjects. Maybe you still have a photo from the day of the recordings?

If not, I hope you could maybe memorize it? To help with this, I made the following sketch with my best guess of the sensor placement. The red captions relate to the unknown sensors. Please correct where I was wrong.

<img width="548" alt="imu_order" src="https://user-images.githubusercontent.com/32466285/122066127-c244ca80-cdf2-11eb-96fa-4f170c7effb6.png">

Finally, I'd like to create some value for future research on this. Thus, I will post the indices of the corresponding SMPL and SMPL-X vertices here once I get a good understanding of where exactly they are located.

Many thanks for your time and best wishes,
Nicola

**Comment by kaufManu** [comment]
Hi Nicola,

To capture reference poses with 17 IMU sensors we used the placement as indicated by Xsens and using their mocap suit, with two exceptions:
- We didn't use their headband for the head sensor, but the custom hat you see in the picture in your post.
- We didn't place the feet sensors into the shoe lace put velcroed them onto the tip of the feet.

The naming in our original text file might be a bit misleading indeed. This video gives a nice overview how to mount the sensors: https://www.youtube.com/watch?v=6TWrcZ84fR4 The link you posted does not really show the exact position of the sensors, just the bone on which to put them. You would have to adjust your image as follows:
- there's no belly sensor, instead this one goes to the sternum.
- there's no chest sensors, instead those were used for the hand (not the wrist).
- the ankle sensors go onto the tip of the feet as mentioned
- the elbow sensors are located in the middle of the upper arm
- the hip sensors are located in the middle of the thigh, facing outwards

Regarding SMPL vertices: May be @YinghaoHuang91 can help more here? I'm not sure if SIP requires this information as well and if it's possible to retrieve the vertex indices from when we ran the data through SIP.

Best
Manuel

**Comment by nkueng** [comment]
Hey Manuel,

Thanks a bunch for your quick reply! I am glad you guys used the standard Xsens configuration after all. Your naming convention really made me doubt that though 😅 

To summarize your answer: this is the mapping from the names in the dataset to where the sensors were actually located

        [head, spine2, belly, lchest, rchest, lshoulder, rshoulder, lelbow, relbow, lhip, rhip, lknee, rknee, lwrist, rwrist, lankle, rankle]
        [head, pelvis, sternum, lhand, rhand, lshoulder, rshoulder, lelbow, relbow, lhip, rhip, lknee, rknee, lwrist, rwrist, lfoot, rfoot]

and these images illustrate where you placed the sensors (please confirm the placement of "elbow" sensors as facing outward).

<img width="357" alt="Screen Shot 2021-06-16 at 08 22 15" src="https://user-images.githubusercontent.com/32466285/122168651-d7663b80-ce7c-11eb-93ba-53a4319fb2b0.png">

> Regarding SMPL vertices: May be @YinghaoHuang91 can help more here? I'm not sure if SIP requires this information as well and if it's possible to retrieve the vertex indices from when we ran the data through SIP.

You might have misunderstood me there. No need for @YinghaoHuang91 to help out. I am offering to figure out the SMPL indices graphically and post them here for reference.

Cheers,
Nicola

**Comment by YinghaoHuang91** [comment]
@kaufManu @nkueng Yes I also think the answer is detailed enough. As to the SMPL vertices if I remember correctly the indices are directly copied from SIP method. You can find it in the synthetic data generation script. If a proper calibration is done at the start, the orientation will be fine for whatever way you want to place the IMU on the bone. The specific placement of the IMU mainly affects the acceleration readings.

**Comment by nkueng** [comment]
@YinghaoHuang91, you are right: some of the vertices on the SMPL mesh are provided in `genSynData.py`, but those are only the 6 that you used for Deep Inertial Poser. Since I would like to synthesize data for all 17 sensor locations, I had to figure out the vertices manually. Moreover, I wanted to use the updated SMPL-X mesh for which the 6 provided indices are invalid.

Anyways, these are the 17 indices I came up with based on the instructional video for the Xsens MVN setup. When plotting spheres at the specified vertices on the mesh, you get the image below.

``` python
# dictionary that maps Xsens IMU location to vertex id on SMPL-X surface
sensor_vertex_ids = {
    'lwrist': 4858,
    'rwrist': 7559,
    'lknee': 3811,
    'rknee': 6568,
    'head': 8942,
    'pelvis': 5493,
    'lelbow': 3952,
    'relbow': 6700,
    'lhip': 3603,
    'rhip': 6364,
    'lhand': 4617,
    'rhand': 7348,
    'lfoot': 5894,
    'rfoot': 8588,
    'lshoulder': 5462,
    'rshoulder': 8196,
    'sternum': 5528
}
```

![Screen Shot 2021-06-16 at 09 41 44](https://user-images.githubusercontent.com/32466285/122180711-f7036100-ce88-11eb-9c3b-3476ae007b05.png)

Will close once @kaufManu confirms the correctness of the sensor placement on the arm.

Many thanks,
Nicola

**Comment by kaufManu** [comment]
Yes, we placed the sensors on the upper arm facing outwards. Your hand-picked vertices look well within range to the real location to me.

Side note: They say this in the instruction video too, I think, but when you actually record data it is recommended to place the sensors under the last layer of strap, so that they hold more tightly.

Good luck with your project!

**Comment by kaufManu** [comment]
There has been some confusion regarding the order of the IMUs. The file `overview_of_published_data.txt` available with the data download specifies the order as follows:

```
[head, spine2, belly, lchest, rchest, lshoulder, rshoulder, lelbow, relbow, lhip, rhip, lknee, rknee, lwrist, rwrist, lankle, rankle]
```

This is correct, but the naming is a bit misleading. For example, the `lshoulder` sensor is not the one placed on the left shoulder, but the one placed on the left upper arm. The name refers to the anchor joint of the bone segment that the sensor is measuring. I.e. a more intuitive naming that reflects where the sensors were placed would be

```
sensor_placement = ["head", "sternum", "pelvis", "lshoulder", "rshoulder", "lupperarm", "rupperarm", "llowerarm", "rlowerarm", "lupperleg", "rupperleg", "llowerleg", "rlowerleg", "lhand", "rhand", "lfoot", "rfoot"]
```

**Comment by kaufManu** [comment]
A visualization of the sensor placement with aitviewer can be found here: https://github.com/eth-ait/aitviewer/blob/main/examples/load_DIP_IMU.py

**Comment by AnaG18** [comment]
Hi! 

I had a quick question, but I am interested in knowing how you can figure out the vertices manually. I am working with the IMUPoser code and I just can't figure out how to map the joint to the vertices. Any help is greatly appreciated. 

Thanks!

**Comment by kaufManu** [comment]
You can use aitviewer to inspect the vertex IDs. If you hit `I` in the viewer an "inspection" window pops up that displays face IDs, vertex IDs etc. as you hover over them with the mouse. To better see the vertices of the SMPL mesh, right-click on it and select `Mesh > Draw Edges` (can also be selected as a checkbox in the editor menu pane). If you need to access vertex IDs programatically, e.g. printing them when clicking on a vertex, check out the [`vertex_clicking.py`](https://github.com/eth-ait/aitviewer/blob/main/examples/vertex_clicking.py) example.

**Comment by YinghaoHuang91** [comment]
Yes, aitviewer will be perfect for that purpose and many more.

**Comment by bryanbocao** [comment]
> @YinghaoHuang91, you are right: some of the vertices on the SMPL mesh are provided in `genSynData.py`, but those are only the 6 that you used for Deep Inertial Poser. Since I would like to synthesize data for all 17 sensor locations, I had to figure out the vertices manually. Moreover, I wanted to use the updated SMPL-X mesh for which the 6 provided indices are invalid.
> 
> Anyways, these are the 17 indices I came up with based on the instructional video for the Xsens MVN setup. When plotting spheres at the specified vertices on the mesh, you get the image below.
> 
> ```python
> # dictionary that maps Xsens IMU location to vertex id on SMPL-X surface
> sensor_vertex_ids = {
>     'lwrist': 4858,
>     'rwrist': 7559,
>     'lknee': 3811,
>     'rknee': 6568,
>     'head': 8942,
>     'pelvis': 5493,
>     'lelbow': 3952,
>     'relbow': 6700,
>     'lhip': 3603,
>     'rhip': 6364,
>     'lhand': 4617,
>     'rhand': 7348,
>     'lfoot': 5894,
>     'rfoot': 8588,
>     'lshoulder': 5462,
>     'rshoulder': 8196,
>     'sternum': 5528
> }
> ```
> 
> ![Screen Shot 2021-06-16 at 09 41 44](https://user-images.githubusercontent.com/32466285/122180711-f7036100-ce88-11eb-9c3b-3476ae007b05.png)
> 
> Will close once @kaufManu confirms the correctness of the sensor placement on the arm.
> 
> Many thanks, Nicola

Hi @nkueng, thanks for manually checking the vertex indices!

I am trying to figure the 24 (and 17 in the paper) joint vertexes in SMPL (here it showed SMPL-X). **Q1:** @kaufManu do you suggest if I should do that manually inspecting the joints one by one? I searched the code and the paper but did not find those detail. Sorry if I missed it.

**Q2:** I am trying to use exactly the same ```17``` IMUs in the paper, the joint indices of
```
sensor_placement = ["head", "sternum", "pelvis", "lshoulder", "rshoulder", "lupperarm", "rupperarm", "llowerarm", "rlowerarm", "lupperleg", "rupperleg", "llowerleg", "rlowerleg", "lhand", "rhand", "lfoot", "rfoot"]
```
seem to be listed here
https://github.com/eth-ait/dip18/blob/eadd5f60db8975d499651d34268ba97b5282dccc/train_and_eval/utils.py#L26
since ```len(SMPL_MAJOR_JOINTS)=15```, I guess the rest two are ```20``` and ```21``` as listed in
https://github.com/eth-ait/dip18/blob/eadd5f60db8975d499651d34268ba97b5282dccc/train_and_eval/utils.py#L28


But I am not sure if it is correct. Example, ```pelvis```'s index should be ```0``` according to https://github.com/Xinyu-Yi/TransPose/issues/69#issuecomment-2477685981, but it is not listed in ```SMPL_MAJOR_JOINTS```. It would be appreciated if you can clarify that.
**Update**, sorry the index here should follow this https://github.com/FIGLAB/IMUPoser/blob/ca94eac4be156b5f16e6ed0d0953d0bac6084c1a/src/imuposer/config.py#L65-L83

Thanks!

**Comment by bryanbocao** [comment]
I try my best to follow https://github.com/eth-ait/dip18/issues/16#issuecomment-862140533, and manually select the vertexes for SMPL model:
```
sensor_vertex_ids = {
        'lwrist': 2185,
        'rwrist': 5644,
        'lknee': 1079,
        'rknee': 4565,
        'head': 3761,
        'pelvis': 2914,
        'lelbow': 1315,
        'relbow': 4795,
        'lhip': 959,
        'rhip': 4447,
        'lhand': 2005,
        'rhand': 5466,
        'lfoot': 3343,
        'rfoot': 6742,
        'lshoulder': 734,
        'rshoulder': 4218,
        'sternum': 2812
    }
```

You may try the visualization code here: https://github.com/bryanbocao/IMUPoser/blob/main/scripts/1_preprocessing/visualize_body_part_segmentation_17_joints.py.

The 17 IMUs are highlighted in red:
![Screenshot from 2024-11-16 20-23-01](https://github.com/user-attachments/assets/cedbf88f-3575-4a8b-bbe6-b2f4be1514b1)
![Screenshot from 2024-11-16 20-23-34](https://github.com/user-attachments/assets/a003ec9d-65dd-428b-ab7d-5cd5f4679527)
![Screenshot from 2024-11-16 20-23-45](https://github.com/user-attachments/assets/6041ce01-1bd4-4c31-b5c5-91cdf5c73233)
![Screenshot from 2024-11-16 20-24-20](https://github.com/user-attachments/assets/fb581729-2617-44c2-9dd8-5d4d303de08a)
![Screenshot from 2024-11-16 20-25-19](https://github.com/user-attachments/assets/026b5502-a455-45c2-9288-3dc2244b0bad)
![Screenshot from 2024-11-16 20-26-39](https://github.com/user-attachments/assets/f6181762-36fc-4f89-871b-6bffc4abb8f0)

The head, sternum and pelvis still have slight off but they are the closest I can find.
