### ISSUE TITLE
How can I get the position of each joint?

### ISSUE THREAD

**Issue by Whisper-Cao** [eth-ait/dip18#17]
In data folder DIP_IMU, the ground truth is provided in the form of joint angle data['gt']. Is there any way to translate the joint angle to the 3D position of each joint?

**Comment by kaufManu** [comment]
Hi,

Yes (and this is also called forward kinematics). You will need the SMPL model for this, which takes as input the joint angles and outputs the vertices and 3D joints. Our synthetic data generation script uses the SMPL model, too, albeit not to extract 3D joints, but it shouldn't be too much work to adapt it (cf. [here](https://github.com/eth-ait/dip18/tree/master/data_synthesis)). If that doesn't work, then I suggest you follow the tutorials on the [AMASS website](https://github.com/nghorbani/amass).

**Comment by Whisper-Cao** [comment]
> Hi,
> 
> Yes (and this is also called forward kinematics). You will need the SMPL model for this, which takes as input the joint angles and outputs the vertices and 3D joints. Our synthetic data generation script uses the SMPL model, too, albeit not to extract 3D joints, but it shouldn't be too much work to adapt it (cf. [here](https://github.com/eth-ait/dip18/tree/master/data_synthesis)). If that doesn't work, then I suggest you follow the tutorials on the [AMASS website](https://github.com/nghorbani/amass).

That works, thank you!

**Comment by Whisper-Cao** [comment]
> Hi,
> 
> Yes (and this is also called forward kinematics). You will need the SMPL model for this, which takes as input the joint angles and outputs the vertices and 3D joints. Our synthetic data generation script uses the SMPL model, too, albeit not to extract 3D joints, but it shouldn't be too much work to adapt it (cf. [here](https://github.com/eth-ait/dip18/tree/master/data_synthesis)). If that doesn't work, then I suggest you follow the tutorials on the [AMASS website](https://github.com/nghorbani/amass).

That works, thank you!
