### ISSUE TITLE
The TotalCapture SMPL poses

### ISSUE THREAD

**Issue by xdtcssdi** [eth-ait/dip18#21]
Hi!
Thank you very much for the DIP dataset. Can you please provide the the TotalCapture SMPL poses (contain acc , ori and poses).I have got the Totalcapture raw dataset, but processing it is a big challenge.
Thanks!

**Comment by kaufManu** [comment]
Hi, no problem, but could you please send us an e-mail? Thanks!

**Comment by kaufManu** [comment]
For future reference, the SMPL version of TotalCapture can be downloaded from the [project page](https://dip.is.tue.mpg.de/index.html) under `ORIGINAL TotalCapture DATA W/ CORRESPONDING REFERENCE SMPL Poses` in the Downloads section.
