### ISSUE TITLE
AMASS

### ISSUE THREAD

**Issue by BexHamer** [eth-ait/dip18#24]
Thank you for your work. I would like to ask if the dataset you provide, AMASS, is already calibrated and pre-processed? Can I feed it directly into the network?

**Comment by YinghaoHuang91** [comment]
Yes, I think the version of AMASS provided with this project can be directly fed into the network. 
![image](https://user-images.githubusercontent.com/13058193/167226348-b71c1dd5-5406-4307-b30f-5b9aa49d7335.png)
