### ISSUE TITLE
Questions about formula in the paper

### ISSUE THREAD

**Issue by SizheAn** [eth-ait/dip18#25]
Hi,

In the paper, I see such expression: 
![image](https://user-images.githubusercontent.com/87412724/165350558-752bcaa8-309e-45e5-9ae8-f9539694a1b7.png)
Does it mean F^S * R^IS = F^I or the other way around: F^I * R^IS = F^S?

Thanks.

**Comment by YinghaoHuang91** [comment]
R^{IS} means the transformation from frame F^S to F^I. Namely, if one rotation is represented S in F^S and I in F^I, then the relationship between them is: I = R^{IS} * S.
