### ISSUE TITLE
How can we get the 'gt' from our own IMU datas?

### ISSUE THREAD

**Issue by xinzi2018** [eth-ait/dip18#27]
`- data['gt']: A numpy-array of shape (seq_length, 72). Corresponds to the SMPL poses computed with SIP using all 17 sensors. The SMPL pose parameters are stored in the angle-axis format (3 joint angles per 24 joints = 72).`
 is mentioned in 
`overview_of_published_data.txt`.

Now I read the data (accs, rots, etc) through my IMUs, but what should I do to get the pose?
I also didn't find the code corresponding to the paper(SIP):
`
Sparse Inertial Poser:
Automatic 3D Human Pose Estimation from Sparse IMUs
`

**Comment by YinghaoHuang91** [comment]
Hi please check Section 5.2.3 of the main paper. There are some commercial solutions like XSens (https://www.xsens.com/) to capture the whole body motion, then the poses can be converted into SMPL format.
