### ISSUE TITLE
How to calibrate the imu data of totalcapture?

### ISSUE THREAD

**Issue by zxxtxwd** [eth-ait/dip18#28]
Hi, thanks for your excellent work. 
Now I have the raw totalcapture datasets in https://cvssp.org/data/totalcapture/ and the smpl gt data in https://dip.is.tuebingen.mpg.de/ . The TotalCapture_Real.zip only contains calibrated 6 imu data. I want to use the other imu for my work. I have tried the method in "Real-Time full-body motion capture from video and IMUs".  The formula is 
$R_{b_{i}}^{g}=R_{i g} \cdot R_{i} \cdot R_{i b}^{-1}$ 
where R_ig and R_ib are in *_calib_imu_ref.txt and *_calib_imu_bone.txt respectively. But the result is wrong in visualization.
I also tried the calibration procedure mentioned in dip paper, and the result is wrong.  Maybe I missed something important. 
Would you help me provide the critical code for calibrating the imu ori and acc ?
Thank you very much!

**Comment by YinghaoHuang91** [comment]
Can you write us an email? The code will be sent to you via the email. Thanks.
