### ISSUE TITLE
OS, cuDNN, Anaconda versions

### ISSUE THREAD

**Issue by glisca** [eth-ait/dip18#3]
Hi there,

could you please specify more precisely the versions of the OS, cuDNN and Anaconda which you tested the code with?
Thank you in advance!

**Comment by kaufManu** [comment]
Hi glisca,

For training we used both Ubuntu 16.04 and Windows 10. The live-demo ran on Windows 10 only. I don't quite remember the cuDNN version, but I guess whatever was compatible with Tensorflow 1.4 at the time, so probably CUDA 8 and cuDNN 6. I'm clueless what Anaconda version we used (I guess 3.x?), but it also shouldn't matter that much.

**Comment by glisca** [comment]
Hi @kaufManu,

thanks for your reply! It works with cudnn7.1.3 which automatically installs cuda8.0_0 which is required by the Tensorflow1.4. And, yes you are right, the Anaconda version matters less. It works with both Anaconda2 and Anaconda3. So all in all everything is clear :). Thanks again!
