### ISSUE TITLE
PyTorch version?

### ISSUE THREAD

**Issue by bryanbocao** [eth-ait/dip18#32]
Is there a PyTorch version? Thanks!

**Comment by kaufManu** [comment]
Unfortunately not - may be you can check with the authors of [PIP](https://github.com/Xinyu-Yi/PIP) if they re-implemented it in PyTorch for their evaluation purposes.

We'd be happy to accept PRs for a PyTorch version implementation.

**Comment by bryanbocao** [comment]
@kaufManu Great. Thanks for the reference!
