### ISSUE TITLE
 Inquiry about the Discrepancy in Sequences between DIP_IMU.zip and DIP_IMU_nn.zip

### ISSUE THREAD

**Issue by Jaceyxy** [eth-ait/dip18#36]
HI ,I am writing to inquire about a discrepancy I noticed in the DIP_IMU dataset. In the DIP_IMU.zip file, it appears that there are a total of 19 sequences for subjects 9 and 10. However, when I checked the imu_own_test.npz file in the DIP_IMU_nn.zip, there are only 18 sequences available for these subjects.Could you kindly explain the reason for the difference in the number of sequences between the two versions of the dataset?

**Comment by kaufManu** [comment]
Hi, thanks for noticing this, I actually wasn't aware. I think what happened is that one of those sequences was not yet ready when ran the evaluations on our test set, but we still ended up publishing it as part of the DIP-IMU dataset. I checked the old files (as far as it was possible) and it seems that we ran the evaluations on the 18-sequence version (i.e. `DIP_IMU_nn.zip`). Unfortunately I don't really have a way to verify this - It might be worth reaching out to the authors who published works after DIP to see whether they used the 18-sequence or 19-sequence version (like PIP, for instance) to make sure that your evaluations are comparable.
