### ISSUE TITLE
Can we apply the SMPL human poses to URDF avatar?

### ISSUE THREAD

**Issue by Zweisteine96** [eth-ait/dip18#37]
Hi,

First thank you so much for the wonderful work!
I'm currently working with DIP-IMU dataset. The learning targets are SMPL pose parameters, more specifically, the joints orientation w.r.t., their parent link. Is it possible to apply these joints' orientations to a URDF model? For instance, ignoring the deformation, we give the URDF model such a vector [root_pos, root_ori, joints_ori], such that the corresponding motions can also be retargeted to this URDF avatar. Or do we need some further mapping or analytical computations?

Many thanks for considering my request.

**Comment by kaufManu** [comment]
Hi,

This is possible, but not something that I'm familiar with. A mapping is indeed required, here's some more resources that might help you:
- A publication from our group that does that: https://eth-ait.github.io/phys-fullbody-grasp/
- Ye Yuan et al. describe it in their paper: https://arxiv.org/pdf/2104.00683.pdf
- Zhengyi Luo et al. published code that might be helpful, too: https://github.com/KlabCMU/KinPoly

Hope that helps.
