### ISSUE TITLE
Synthetic data generation

### ISSUE THREAD

**Issue by glisca** [eth-ait/dip18#5]
Hi there,

do you intend to release the code which you implemented for synthetic data generation from the AMASS dataset?

Thanks a lot!

**Comment by YinghaoHuang91** [comment]
We planned to release it, but not now. We might release this part of code sometime next year. Please keep an eye on this repository if you are interested. Thanks!

**Comment by xspc** [comment]
Hi, 

Thanks so much for such an excellent work. I wonder whether you have released the relevant code to generate synthetic IMU data from the AMASS dataset? Or could you tell us the implementation method to get synthetic IMU data using forward kinematics?

Thanks a lot!
