### ISSUE TITLE
DLLs for setting up the Unity3D project

### ISSUE THREAD

**Issue by glisca** [eth-ait/dip18#6]
Hi there,

I try to setup the Unity3D project by following the instructions from the [Setting up the Unity Project](https://github.com/eth-ait/dip18/tree/master/live_demo#setting-up-the-unity-project) and I noticed that:
- I had to make a copy of `System.Windows.Forms.dll` and `WindowsBase.dll` into the `XSensStream` directory which I created.
- the files `MasterInfo.cs` and `DeviceInfo.cs` are missing from the directory: `%MT_SOFTWARE_SUITE%/MT SDK/Examples/awindamonitor_csharp/`. I copied them from `%MT_SOFTWARE_SUITE%/MT SDK/Examples/xda_csharp/` and got stuck while trying to get Unity3D to recognize the `xsensdeviceapi_csharp64.dll` file.
- all files `DeviceInfo.cs`,  `MasterInfo.cs`, `MyEventArgs.cs` and `MyXda.cs` are present in the `%MT_SOFTWARE_SUITE%/MT SDK/Examples/xda_csharp` directory. I copied them from here and still got stuck while trying to get Unity3D to recognize the `xsensdeviceapi_csharp64.dll` file.

Do you have some tips for me on how to move on with setting up the Unity3D project?

Many thanks in advance!
Gheorghe

**Comment by glisca** [comment]
Hi there,

after tying further I got the Unity3D client running by:
- copying into the `XSensStream`:
  - the entire `%MT_SOFTWARE_SUITE%\MT SDK\Examples\xda_csharp\wrap_csharp64` rather than `%MT_SOFTWARE_SUITE%/MT SDK/Examples/awindamonitor_csharp/wrap_csharp64`
  - the `System.Windows.Forms.dll` from `C:\Windows\Microsoft.NET\Framework\v4.0.30319` and `WindowsBase.dll` from `C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0`
- copying into the Unity3D directory: `C:\Program Files\Unity\Hub\Editor\2017.3.1f1\Editor` all 3 DLLs: `xsensdeviceapi_csharp64.dll`, `xsensdeviceapi64.dll` and `xstypes64.dll` from the`%MT_SOFTWARE_SUITE%\MT SDK\Examples\xda_csharp\` directory.
- fixing the typo: `MyMtwCallback` into `MyMtCallback` from the `read_mtw.cs` file.

Now the python server and the Unity3D client run properly and I can experiment further with them.

Kind regards and thanks a lot for releasing this source code!
Gheorghe

**Comment by kaufManu** [comment]
Hi @glisca 

Glad it is working now and thanks for documenting the required changes here for future reference!
