### ISSUE TITLE
Can I change the position and the number of the sensors?

### ISSUE THREAD

**Issue by MaxMaxinne** [eth-ait/dip18#7]
Thanks so much for such a nice work.I am wandering wheter I can change the position and the number of the sonsors.If I could, is the dataset still available for training?Should I modify the structure of the net?

**Comment by MaxMaxinne** [comment]
Whats more,could I use another kind of senors insead of the sensors produced by Xsense?

**Comment by kaufManu** [comment]
Hi @MaxMaxinne 

In theory you can pick any vertex on the SMPL model to place the virtual IMUs. However, I would suggest re-training the network in this case, which probably requires to re-synthesize the data at these new locations. Whether or not you have to change the network is difficult to say - I personally would at least run a couple of experiments to see how the performance changes.

You can use other IMUs, but you would have to do some coding to interface with their SDK for the real-time demo (assuming they provide such an SDK in the first place). Note that performance of IMUs can vary drastically between type or vendor. In general I'd suggest using 9-dof IMUs (i.e. IMUs containing 3-axis gyro, 3-axis accelerometer and 3-axis magnetometer) and you would also have to look into time-synchronizing different sensors. All of this can be very time-consuming and require a lot of engineering.

**Comment by MaxMaxinne** [comment]
> Hi @MaxMaxinne
> 
> In theory you can pick any vertex on the SMPL model to place the virtual IMUs. However, I would suggest re-training the network in this case, which probably requires to re-synthesize the data at these new locations. Whether or not you have to change the network is difficult to say - I personally would at least run a couple of experiments to see how the performance changes.
> 
> You can use other IMUs, but you would have to do some coding to interface with their SDK for the real-time demo (assuming they provide such an SDK in the first place). Note that performance of IMUs can vary drastically between type or vendor. In general I'd suggest using 9-dof IMUs (i.e. IMUs containing 3-axis gyro, 3-axis accelerometer and 3-axis magnetometer) and you would also have to look into time-synchronizing different sensors. All of this can be very time-consuming and require a lot of engineering.

got it!Thanks a lot.
