### ISSUE TITLE
The meaning of training data entries

### ISSUE THREAD

**Issue by glisca** [eth-ait/dip18#8]
Hi there,

I am looking at the training file: `./Synthetic_NPZ/training.npz` from `SyntheticNPZ.zip` and I see that the dictionary it contains had the following entries:
  - `data_id` with shape `(32092,)` : `n/a`
  - `file_id` with shape `(32092,)` : names of files
  - `orientation` with shape `(32092,)` : entries with the shape `(300, 45)`
  - `acceleration` with shape  `(32092,)` : entries with the shape `(300, 15)`
  - `smpl_pose` with shape `(32092,)` : entries with the shape `(300, 135)` 
  - `preprocessing` [1] with shape  `(32092,)`
  - `statistics` [2] with shape `(32092,)`

My questions:
1. When and how did you compute the "preprocessing" entries [1] and the "statistics" entries [2]?
2. How are the "preprocessing" [1] and "statistics" entries [2] used and which parts of the training / live demo depend on them?

Many thanks in advance!

**Comment by YinghaoHuang91** [comment]
This is also part of the data pre-procssing before the training/testing data is fed into the neural network. It's described in the Section C and Appendix, on Page 14, titled "Zero-mean unit-variance". Please refer to the related text for more details. 

Hope it helps. Best!

**Comment by glisca** [comment]
Super! Thanks a lot for clarification!

kind regards,
